# version: '3.1'

# services:
#   php-env:
#     build: .
#     volumes:
#       - ./ /var/www/html
#     ports:
#       - 9000:80  

#   mysql_db:
#     image: mysql:latest
#     command: --default-authentication-plugin=mysql_native_password
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root

#   phpmyadmin:
#     image: phpmyadmin:latest
#     restart: always
#     ports:
#       - 9001:80
#     environment:
#       -PMA_ARBITRARY=1

version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www/html/

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
